### ISSUE TITLE
[10.26 - ] Todo

### ISSUE THREAD

**Issue by Jongminfire** [SW-Maestro-TeamGDB/Pentatonic-Web#17]
## 페이지 전체
- [x] 검은색 버튼 보라색으로 변경
- [x] 데스크탑 모바일 검사 함수 `isMobile` 수정

## 라운지 홈
- [x] 라운지 홈에서 쿼리 두번 나누지 않고 한번에 호출
- [x] 떠오르는 솔로 커버, 떠오르는 밴드 커버 페이지 생성
- [x] 떠오르는 커버 밑에 라운지 페이지 접근 버튼 추가
- [x] 떠오르는 커버 반응형 width에 따른 커버 로드

## 라운지 페이지
- [x] 자신의 커버 삭제하고 나오면 커버 그대로 남아있음

## 스튜디오 홈
- [x] 밴드커버 녹음하기 -> 밴드커버 만들기
- [x] 스튜디오 배너 각 아이템에 문구를 넣지말고 문구는 고정하는 방식으로 변경
- [x] 스튜디오 배너 커버 제목과 원곡 정보 같이 뜨도록 변경
- [x] 스튜디오 홈 정적 이미지 앱이랑 통일
- [x] 이런 곡 어때요 반응형 width에 따른 음악 로드

## 음원 상세 페이지
- [x] 커버룸 만들기 -> 커버 만들기로 버튼 문구 수정
- [x] 커버 만들기와 라이브러리 녹음 설명하는 도움말 tooltip 추가

## 커버 폼
- [x] 제공 반주에 반주에 따라 부분적으로 녹음되어 있을 수 있다는 문구 추가

## 커버 녹음
- [x] 녹음 페이지 아이콘 수정 및 문구 추가
- [x] 녹음 가공 페이지 다시 녹음하기 오류 확인
- [x] 녹음 페이지 뒤로가기, 다른 메뉴 누를 시 페이지 이탈 모달 구현
- [x] 커버 녹음 크롬 브라우저 권장 모달 추가

## 라이브러리
- [x] 라이브러리 음원 하나만 재생 할 수 있도록 변경
- [x] 라이브러리 date format YYYY-MM-DD HH:MM 로 변경

## 아티스트
- [x] 밴드 랭킹 -> 밴드 커버 랭킹 문구 수정
- [x] 밴드 랭킹, 아티스트 랭킹 페이지 문구 수정 `좋아요를 가장 많이 받은 밴드 커버를 둘러보세요`,`펜타토닉에서 가장 인기있는 아티스트들을 둘러보세요`
- [x] 아티스트 랭킹 하트 표시 색 추가

## 프로필
- [x] 팔로우 취소 시 모달 삭제
