### ISSUE TITLE
[11.02 - ] Todo

### ISSUE THREAD

**Issue by Jongminfire** [SW-Maestro-TeamGDB/Pentatonic-Web#18]
## 페이지 관련
- [x] 솔로커버 페이지에서 프로필 이미지 누르면 프로필 페이지로 이동하도록 변경
- [x] 곡 선택 페이지 태블릿 화면에서 장르 한줄 넘어가는 것 수정
- [x] 헤더 로그인 버튼 태블릿 화면에서 한줄 넘어가는 것 수정
- [x] 곡 상세 페이지 도움말 버튼 크게 변경
- [x] 토큰 통해 유저 정보 받아오는 쿼리 연결
- [x] 랭크 리스트 자기소개 문구 ellipsis 처리
- [x] 댓글 순서 이상한 이슈
- [x] 프로필 팔로우 -> 팔로잉 으로 문구 수정

## 기능 관련
- [x] Song lyrics 속성 데이터 바인딩
- [x] 관리자페이지 Song lyrics 등록 추가
- [x] 곡 상세페이지에서 songURI를 통한 미리듣기 기능
- [x] 커버 등록 페이지 Free (그 외 반주 추가)
- [x] 커버 룸 페이지 Free 포지션 경우 filter 해제
- [x] 프로필 결제 컨테이너 생성
- [x] 결제 기능 연동
- [x] 소셜 미디어 링크 연동
- [x] 커버룸 도네이팅 버튼 및 모달 생성
- [x] 커버룸 참여 시 제공반주 안누르면 빈 inst 생성
- [x] 포지션 참여했는데 좋아요 없을 시 빈 화면 나오는 이슈
- [x] 새로운 악기 포지션 추가
- [x] 녹음기능 데스크탑 일때만 막도록 변경
