### ISSUE TITLE
CoverRoom todo

### ISSUE THREAD

**Issue by Jongminfire** [SW-Maestro-TeamGDB/Pentatonic-Web#8]
## 음원

- [x] #9
- [x] 음원 컨트롤
- [x] 세션 선택
- [x] 세션 미 선택 시 안내 모달
- [x] 라이브러리 참가 기능
- [x] 라이브러리 필터 기능

## 커버 룸

- [x] 댓글 표시
- [x] 댓글 삭제
- [x] 댓글 수정
- [x] 세션 닉네임 표시
- [x] 세션 밴드 크리에이터 표시

## 커버 관리 

- [x] 밴드 좋아요 기능
- [x] 밴드 삭제 기능
- [x] 밴드 방출 기능
- [x] 밴드 탈퇴 기능

## 싱글 커버

- [x] CoverBy 리스트 컴포넌트 제작
